### ISSUE TITLE
ScalaCheck properties fail to compile on 2.10

### ISSUE THREAD

**Issue by markhibberd** [argonaut-io/argonaut#11]
See: https://travis-ci.org/markhibberd/argonaut/jobs/3745016

140[info] Compiling 9 Scala sources to /home/travis/builds/markhibberd/argonaut/target/scala-2.10/test-classes...
141[error] /home/travis/builds/markhibberd/argonaut/src/test/scala/argonaut/JsonTest.scala:30: could not find implicit value for parameter a2: org.scalacheck.Arbitrary[argonaut.Json.JsonArray => argonaut.Json.JsonArray]
142[error]       forAll((j: Json, k: JsonArray => JsonArray) =>
143[error]             ^
144[error] /home/travis/builds/markhibberd/argonaut/src/test/scala/argonaut/JsonTest.scala:54: could not find implicit value for parameter a1: org.scalacheck.Arbitrary[argonaut.Json.JsonArray]
145[error]       forAll((a: JsonArray) =>
146[error]             ^
147[error] two errors found
148[error](test:compile) Compilation failed
149[error] Total time: 65 s, completed Dec 19, 2012 7:04:46 PM
